package intro;
/**Description:
 * Write a program that randomly generates an integer greater than or equal to 0 and less than 100. The
 program then prompts the user to guess the number. If the user guesses the number correctly, the program
 outputs an appropriate message. Otherwise, the program checks whether the guessed number is less than
 the random number. If the guesses number is less than the random the number generated by the program,
 the program outputs the message, “Your guess is lower than the number”; otherwise, the program output
 the message, “Your guess is higher than the number”. The program then prompts the user to enter another
 number. The user is prompted to guess the random number until the user enters the correct number. You
 can use the method random of the class Math to generate a random number. To be specific, the expression:
 Math.random()
 */

import java.util.Scanner;
public class Practice36 {
    public static void main(String args[]){

        //Scanner to get input from user
        Scanner reader = new Scanner (System.in);

        //declaring variables
        int guessNumber;
        guessNumber = (int) (Math.random() * 99 + 1);
        int guess = 0;
        int count = 0;

        //Checking if guess is right
        do {
            //getting input
            System.out.println("Enter your guess [1-100]: ");
            guess = reader.nextInt();

            if(guess == guessNumber){
                //prints if the correct number was guessed
                System.out.println();
                System.out.println("Your guess is correct. Well done!");
            } else if (guess < guessNumber){
                //prints if guess is lower
                System.out.println();
                System.out.println("Your guess is lower than the number.");
            } else if (guess > guessNumber){
                //prints if guess is higher
                System.out.println();
                System.out.println("Your guess is higher than the number.");
            }
        } while (guess != guessNumber);

    }
}
